all changes
spinel/go-musthave-shortener pull request #1
Opened 2021-08-23 19:13 UTC by spinel

2021-08-23 22:40 UTC, iTiky requested changes
Ты первый, кто прислал работу на проверку и это классно. В целом - код рабочий. Большинство моих комментариев относятся с Go-стилю и best practices для Go.

Общие моменты:
1. Нет автотестов. В репо Яндекса я заметил, что не прошла `go vet` проверка, обрати на нее внимание.
2. Нет godoc-комментариев.
3. Некоторые моменты, что я указал, будут рассмотрены далее в материалах курса. Я посчитал нужным обратить на них внимание уже сейчас.

2021-08-23 22:40 UTC, iTiky commented on cmd/shortener/main.go
> +		panic("no repo")
Лучше добавить контекст ошибки в панику, иначе сложнее дебажить ошибку инициализации.

2021-08-23 22:40 UTC, iTiky commented on cmd/shortener/main.go
> +	log.Fatal(http.ListenAndServe(":8080", nil))
Сервер можно запускать в Go-рутине, чтобы при возникновении ошибки, залогировать ее с контекстом (где произошла).

2021-08-23 22:40 UTC, iTiky commented on internal/app/model/shortener.go
> +type Shortener struct {
Из названия типа не понятно его предназначение. Можно добавить поясняющий комментарий к типу или подумать над другим именем структуры.

2021-08-23 22:40 UTC, iTiky commented on internal/app/model/shortener.go
> +type Shortener struct {
Здесь и далее по коду отсутствуют godoc комментарии перед функциями, типами, интерфейсами. Наличие godoc-ов сильно облегчает понимание проекта. Я бы посоветовал взять за правило добавлять описание перед каждым публичным типом и методом, главное - не забывать ставить точку в конце предложений (иначе линтеру это не понравится).

2021-08-23 22:40 UTC, iTiky commented on internal/app/router/router.go
> +	r.HandleFunc("/{id:[0-9a-z]+}", handler.GetShortenerHandler(repo))
👍 за regexp

2021-08-23 22:40 UTC, iTiky commented on internal/app/router/router.go
> +	r.HandleFunc("/", handler.CreateShortenerHandler(repo))
`CreateShortenerHandler` и `GetShortenerHandler`. Лучше привести имя функции к одному стилю, например `NewShortenerHandler` и `NewGetShortenerHandler`.

2021-08-23 22:40 UTC, iTiky commented on internal/app/repository/repository.go
> +	SaveShortener(string, *model.Shortener) error
Лучше придерживаться immutable стиля везде где можно, чтобы избежать возможных ошибок. В данном случае не ясно, зачем передавать указатель. Скорее всего, это связано с внутренней имплементацией Repository, но объект модели, всегда стоит передавать по значению, т.к. в теле функции он не должен меняться.

2021-08-23 22:40 UTC, iTiky commented on internal/app/repository/repository.go
> +	GetShortenerBy(string) (*model.Shortener, error)
При описании интерфейсов, обычно именуют входные аргументы и возвращаемые значения (если их много) для читабельности кода. В данном случае, что-то типо:
```go
// GetShortenerBy возвращает ... по ...
GetShortenerBy(shortenerID string) (*modelShortener, error)
```

2021-08-23 22:40 UTC, iTiky commented on internal/app/repository/store.go
> +type Store struct {
Тип `Store` используется другими пакетами, поэтому лучше скрывать его внутреннюю имплементацию и добавить методов для взаимодействия с ним (`Exists`, `Add`, `Get` и т.д.). В объекте есть мапа и это потенциально опасно давать к ней прямой доступ вне этого пакета.

2021-08-23 22:40 UTC, iTiky commented on internal/app/repository/store.go
> +	Shortener Repository
Чуть нарушена логика зависимостей. `Store` - это уровень БД, а `Repository` - это уровень сервиса, т.о. это сервис должен включать в себя базу, а не наоборот. Другими словами, `Repository` занимается бизнес-логикой приложения и то, что у него под капотом какая-то БД, нужно скрывать от уровня выше (уровень API).

2021-08-23 22:40 UTC, iTiky commented on internal/app/repository/store.go
> +	return &store, nil
В Go-community принято обособлять `return` новой строкой (в том числе, когда `return` находится внутри `if`-а).

2021-08-23 22:40 UTC, iTiky commented on internal/app/repository/store.go
> +	var store Store
При объявлении переменной через `var`, разработчик ожидает, что она будет инициализирована неявно (например, через `json.Unmarshal`). В данном случае, инициализация следует за этой строкой. Я бы изменил это на Go-стиль объявления:
```go
store := Store{
  MemoryDB: ...
  Shorneter: ...
}
```

2021-08-23 22:40 UTC, iTiky commented on internal/app/repository/web/shortener.go
> +	Memory map[string]*model.Shortener
`ShortenerRepo` является имплементацией `Repository`. Чтобы показать это явно и добавить проверку на этапе компиляции, можно добавить строку вида:
```go
var _ Repository = (*ShortenerRepo)(nil)
```
Так же, это поможет другому разработчику понять, что это за тип и для чего он нужен.

2021-08-23 22:40 UTC, iTiky commented on internal/app/helper/generate.go
> +	chars := []rune(
Этот слайс лучше вынести в приватную глоб. переменную, т.к. это уменьшит количество лишних аллокаций при вызове этой функции.

2021-08-23 22:40 UTC, iTiky commented on internal/app/helper/generate.go
> +	var b strings.Builder
👍 за builder.

2021-08-23 22:40 UTC, iTiky commented on internal/app/helper/generate.go
> +type GeneratedString string
Обычно, строку переопределяют в другой тип, чтобы реализовать таким образом enum в Go. В данном случае тип `GeneratedString` не обладает какими-либо методами, т.е. не расширяет обычный `string`. В проектах на Go стараются не переопределять стандартные типы без строгой необходимости, т.к. это излишне усложняет код и ухудшает читабельность.

2021-08-23 22:40 UTC, iTiky commented on internal/app/handler/handler.go
> +func CreateShortenerHandler(repo *repository.Store) func(w http.ResponseWriter, r *http.Request) {
Золотое правило Go: "принимаем интерфейс, возвращаем указатель". В данном случае нужно ожидать объект, реализующий интерфейс репозитория и работать с ним через методы интерфейса.
В данном случае, лучше возвращать `http.Handler` (это общая практика).

2021-08-23 22:40 UTC, iTiky commented on internal/app/handler/handler.go
> +		url := string(body)
Логические части лучше отделять пустой строкой. Опять же, чтобы легче воспринимать код.

2021-08-23 22:40 UTC, iTiky commented on internal/app/handler/handler.go
> +		codeString := string(code)
Тут мы приводим тип к строке, т.е. наличие типа `GeneratedString` кажется лишним.

2021-08-23 22:40 UTC, iTiky commented on internal/app/helper/generate.go
> +package helper
`helpers` / `utils` это как прийти в магазин музыкальных инструментов и начать играть Smoke on the water. Лучше так не делать =)
Я бы посоветовал использовать `pkg`, где хранить все вспомогательные объекты и функции.

2021-08-23 22:40 UTC, iTiky commented on internal/app/handler/handler.go
> +		id := r.URL.Path[1:]
Я понимаю, что это маловероятно, но тут может быть паника, если `Path` - пустой.
Можно воспользоваться `url.Parse` и брать там basePath. Либо `strings.Split` с проверкой длины слайса.
Я считаю, что лучше добавить проверок, чем потом словить панику.

2021-08-23 22:40 UTC, iTiky commented on internal/app/repository/store.go
> +	MemoryDB  map[string]*model.Shortener
Я бы не стал хранить мапу указателей. map или slice из указателей это тонкая штука, с ней нужно аккуратно. Например, если удалить слайс из указателей, GC не отчистит память, которую занимают объекты под указателями (об этом будет позже).

2021-08-23 22:40 UTC, iTiky commented on internal/app/handler/handler_test.go
> +	if err != nil {
Лучше использовать метод testify `require.NoError(t, err)`

2021-08-23 22:40 UTC, iTiky commented on internal/app/handler/handler_test.go
> +	for _, tt := range tests {
Через `tt` обычно обозначают `*testing.T` главного теста (TestCreateShortenerHandler в данном случае). Лучше использовать testCase или tc

2021-08-23 22:40 UTC, iTiky commented on internal/app/handler/handler_test.go
> +			if res.StatusCode != tt.want.code {
assert.EqualValues(t, tt.want.code, res.StatusCode)
тут и далее

2021-08-30 11:09 UTC, spinel commented on cmd/shortener/main.go
> +	log.Fatal(http.ListenAndServe(":8080", nil))
обновил

2021-08-30 11:09 UTC, spinel commented on internal/app/model/shortener.go
> +type Shortener struct {
переименовал

2021-08-30 11:09 UTC, spinel commented on internal/app/model/shortener.go
> +type Shortener struct {
везде добавил godoc

2021-08-30 11:10 UTC, spinel commented on internal/app/repository/store.go
> +	MemoryDB  map[string]*model.Shortener
переделал на мапу

2021-08-30 11:11 UTC, spinel commented on internal/app/handler/handler.go
> +		id := r.URL.Path[1:]
обновил

2021-08-30 11:11 UTC, spinel commented on internal/app/handler/handler_test.go
> +	if err != nil {
сделал

2021-08-30 11:12 UTC, spinel commented
merge

2021-08-30 16:28 UTC, iTiky requested changes

2021-08-30 16:28 UTC, iTiky commented on internal/app/pkg/generate.go
> +
Тут newline кажется лишним. В `if` его ставят, если кроме `return` есть еще что-то.

2021-08-30 16:28 UTC, iTiky commented on internal/app/helper/generate.go
> +func NewGeneratedString() (GeneratedString, error) {
Похоже на leftover после merge. Функционал уже есть в /pkg.

2021-08-30 16:28 UTC, iTiky commented on internal/app/model/entity.go
> +// Entity is stored object
Описание типа не даёт достаточно информации о его назначении.

2021-08-30 16:28 UTC, iTiky commented on internal/app/model/entity.go
> +// Entity is stored object
Очень не хватает точки в конце.

2021-08-30 16:28 UTC, iTiky commented on internal/app/router/router.go
> +func Router(repo *repository.Store) *mux.Router {
В Go конструкторы принято начинать с `New`. В данном случае это `NewRouter`.

2021-08-30 16:28 UTC, iTiky commented on cmd/shortener/main.go
> +	go func() {
`http.Handler` регистрирует handler-ы, т.о. запуск этой процедуры в отдельной рутине не нужен.

2021-08-30 16:28 UTC, iTiky commented on cmd/shortener/main.go
> +func main() {
Отсутствует процедура graceful shutdown (завершение работы сервера по сигналу от ОС).

2021-08-30 16:28 UTC, iTiky commented on internal/app/repository/web/entity.go
> +func NewEntityRepo(db map[string]model.Entity) *EntityRepo {
Принимать БД как зависимость сервиса это хорошая идея, но тут ожидается конкретная реализация. 
Я бы заменил `map[string]model.Entity` на интерфейс, а в этот конструктор передавал имплементацию этого интерфейса.
Сейчас будет одна имплементация (in-memory на базе `map`), далее добавится еще одна.

2021-08-30 16:28 UTC, iTiky commented on internal/app/repository/web/entity.go
> +	var repo EntityRepo
Чуть более читабельный вариант:
```go
return &EntityRepo{
    Memory: db,
}
```

2021-08-30 16:28 UTC, iTiky commented on internal/app/repository/web/entity.go
> +	Memory map[string]model.Entity
`Memory` - public свойство. Лучше скрывать детали имплементации и не давать коду извне возможности менять состояние объекта. В данном случае, лучше сделать Memory - приватным полем.

2021-08-30 16:28 UTC, iTiky commented on internal/app/repository/web/entity.go
> +	entity := repo.Memory[id]
Если DB не содержит объекта по ключу `id`, будет возвращен объект `model.Entity` с дефолтными значениями.
Обычно, если подразумевается, что объект может быть не найден, возвращают указатель.
Т.е. ошибка - что-то пошло не так, объект == `nil` - объект не найден.

2021-08-30 16:28 UTC, iTiky commented on internal/app/repository/web/entity.go
> +	_, result := repo.Memory[id]
Я бы заменил `result` -> `found`, т.к. это лучше отражает суть происходящего.

2021-08-30 16:28 UTC, iTiky commented on internal/app/repository/store.go
> +type Store struct {
ИМХО
Я бы убрал `Store` совсем, см. комментарий к типу `EntityRepo`.

2021-08-30 16:28 UTC, iTiky commented on internal/app/repository/web/entity.go
> +type EntityRepo struct {
Я бы сделал `Repositorer` - сущностью, которая хранит всю бизнес-логику. Это означает: 
1. API handler-ы работают с `Repositorer`, а не с БД (`Store` тип).
2. Всю логику работы стоит поместить в `Repositorer`. Сейчас генерацией уникального ID занимаются handler-ы, т.е. бизнес-логика размазана между слоями API и service (repository).
3. Изменить интерфейс `Repositorer`, чтобы его методы решали бизнес-задачу. Сейчас они решают задачу хранения и получения данных.
4. Изменить имя интерфейса `Repositorer`, т.к. это очень generic-имя. Как пример - `URLShortener`, т.е. что-то что занимается сокращением ссылок.
5. Принимать интерфейс БД как зависимость сервиса. Сейчас - сущность более верхнего порядка это `Store`, т.е. БД, а не сервис.

2021-08-30 16:28 UTC, iTiky commented on internal/app/model/entity.go
> +// Entity is stored object
`Entity` хранит только одно поле типа `string` и сразу напрашивается вопрос "а зачем для этого отдельный тип?". На этот вопрос должен отвечать godoc-комментарий.

2021-09-03 16:17 UTC, spinel commented on internal/app/helper/generate.go
> +func NewGeneratedString() (GeneratedString, error) {
да. забыл. убрал

2021-09-03 16:32 UTC, spinel commented on internal/app/router/router.go
> +func Router(repo *repository.Store) *mux.Router {
поправил

2021-09-03 16:32 UTC, spinel commented on internal/app/repository/web/entity.go
> +	Memory map[string]model.Entity
скрыл

2021-09-03 16:33 UTC, spinel commented on internal/app/repository/web/entity.go
> +	_, result := repo.Memory[id]
пофиксил

2021-09-03 16:33 UTC, spinel commented on internal/app/repository/web/entity.go
> +	entity := repo.Memory[id]
добавил проверку

2021-09-03 16:34 UTC, spinel commented on cmd/shortener/main.go
> +	go func() {
поправил

2021-09-03 16:35 UTC, spinel commented on internal/app/model/entity.go
> +// Entity is stored object
вообще хочу хранить net/url, пока временно string поставил, структура на будущее задел)

2021-09-03 17:07 UTC, spinel commented on internal/app/repository/web/entity.go
> +type EntityRepo struct {
не получилось у меня пока это переделать. буду думать и добью в будущих версиях!

2021-09-03 18:38 UTC, spinel commented on internal/app/repository/store.go
> +type Store struct {
убрал

2021-09-03 18:52 UTC, spinel commented on internal/app/repository/web/entity.go
> +type EntityRepo struct {
1. сделал
2. перенес, но хендлер все равно обращается за кодами через интерфейс, не знаю правильно ли это?
3. вроде так?
4. название изменил
5. поправил, Store убрал

2021-09-05 16:49 UTC, iTiky approved these changes

2021-09-10 11:40 UTC, iTiky requested changes
Чисто технически, тесты проходят, требуемый функционал есть. Мои комментарии направлены на разграничение уровней ответственности различных слоёв между собой. Сейчас `main` явно перегружен бизнес-логикой.

2021-09-10 11:40 UTC, iTiky commented on internal/app/config/config.go
> +const defaultServerAddress = "localhost:8080"
Я бы объединил это в один блок ради спасения... читабельности.
```go
const (
  default...
)
```

2021-09-10 11:40 UTC, iTiky commented on internal/app/config/config.go
> +func Get() *Config {
1. По факту, это конструктор, поэтому лучше придерживаться Go-нейминга: `func NewConfig() Config`
2. Указатели лучше использовать только если это необходимо. Например возвращаемый объект может быть `nil` по логике приложения (User не найден в базе). В данном случае, это кажется лишней аллокацией на хипе.

2021-09-10 11:40 UTC, iTiky commented on internal/app/config/config.go
> +	once.Do(func() {
Сейчас это не нужно, но бывает необходимость получить обновленный конфиг еще раз по ходу работы приложения. Например мы хотим, чтобы наше приложение реагировало на изменение конфига "на лету" без перезагрузки. Мне кажется, что `sync.Once` тут лишний. Или я не понимаю логику.

2021-09-10 11:40 UTC, iTiky commented on internal/app/config/config.go
> +		fmt.Println("Configuration:", string(configBytes))
`fmt.Printf("%+v\n", config)` чуть проще решение для вывода настройки в консоль. Но не такое красивое. Если хочется JSON, я бы добавил метод `func (c Config) String() string` к объекту и скрыл эту имплементацию там.

2021-09-10 11:40 UTC, iTiky commented on internal/app/config/config.go
> +	once.Do(func() {
Сейчас config - это глобальная переменная или глобальное состояние. Кажется, что это overengineering как по мне.

2021-09-10 11:40 UTC, iTiky commented on internal/app/handler/handler.go
> +		cfg := config.Get()
Лучше придерживаться функционального подхода, т.е. передавать в функцию все, что ей необходимо для работы. В данном случае ей необходим конфиг. У каждого слоя приложения может быть свой конфиг, получать его извне можно, но для этого обычно реализуют какой-то ConfigProvider, который достаёт конфигурацию по запросу (например идет за секретами в Vault, остальное берет из конфиг-файла и т.д.).
Если хочется более простой реализации, можно создать объект `Handler`, которому передают конфиг как одну из зависимостей. Этот объект уже может создавать `http.Handler` по запросу (по вызову метода).
Все это к тому, что лучше избегать запросов к глобальному состоянию, а лучше формировать локальный и достаточный скоуп, требуемый объекту.

2021-09-10 11:40 UTC, iTiky commented on internal/app/store/store.go
> +	mu          sync.Mutex
`sync.Mutex` чаще всего "вкладывают" в структуру, т.е.:
```go
type Store struct {
  sync.Mutex
  obFileName string
  // ...
}
```

2021-09-10 11:40 UTC, iTiky commented on internal/app/store/store.go
> +	gobFile, _ := os.Open(gobFileName)
Нет обработки ошибки, которая вполне вероятно может возникнуть из-за неверного входа (неверный путь к файлу был передан).

2021-09-10 11:40 UTC, iTiky commented on internal/app/store/store.go
> +	defer s.mu.Unlock()
`defer` обычно ставят как можно ближе к месту его лока. Иначе если между `Lock` и `Unlock` возникнет ошибка, которая приведет к прерыванию выполнения, `Unlock` не будет вызван.

2021-09-10 11:40 UTC, iTiky commented on internal/app/store/store.go
> +	memory := make(map[string]model.Entity)
Я бы выделил `map[string]model.Entity` в отдельный тип на уровне модели. Иначе не понятно что это. Лучше работать с каноничными моделями на уровне бизнес-логики.

2021-09-10 11:40 UTC, iTiky commented on internal/app/store/store.go
> +	s.gobFile.Close()
Если `Store` был создан без конструктора, эта строка может запаниковать (`gobFile == nil`)

2021-09-10 11:40 UTC, iTiky commented on internal/app/config/config.go
> +type Config struct {
Я бы добавил к типу метод `Validate() error`, который вернет читабельную ошибку пользователю, если был передан неверный вход. Иначе пользователь получит ошибку из более "нижних" слоёв, которую будет тяжело понять.

2021-09-10 11:40 UTC, iTiky commented on cmd/shortener/main.go
> +	memory, _ := s.GetData()
Очень сложная логика происходящего. Всё держится на том, что `map` в Go передаётся как reference и изменение в каком-либо месте изменит исходные данные (в данном случае, на уровне БД). Это очень большая когнитивная нагрузка на разработчика. Я бы лучше передал всю БД как зависимость в Repo и работал с базой на уровне бизнес логики приложения, чем вводил такую неявную связь.

2021-09-10 11:40 UTC, iTiky commented on cmd/shortener/main.go
> +		for {
Кажется, что эта часть относится к реализации БД. Как пример: ты подключаешься к Redis и при этом ты не знаешь сколько он поднимает потоков, какие воркеры у него есть, тебе нужен только определенный функционал от него (интерфейс по факту). Здесь та же логика. БД что-то скидывает в файл? Ну хорошо, мы за неё рады, но нам нужно ее создать, проверить что создалась, передать её как зависимость и закрыть по завершении приложения.

2021-09-10 19:30 UTC, spinel commented on internal/app/config/config.go
> +func Get() *Config {
изначально сделал New, но по факту он создается один раз, а обращаться к нему можно потом многократно.

2021-09-10 19:34 UTC, spinel commented on internal/app/config/config.go
> +	once.Do(func() {
если один раз сделать NewConfig и передавать дальше по цепочке, то да. Я синглтон сделал с нацелом на то, чтоб не загружать конфиг, дергая этот метод откуда угодно. Но Переделаю.

2021-09-11 16:53 UTC, spinel commented on internal/app/store/store.go
> +	s.gobFile.Close()
сделал store приватным

2021-09-11 18:43 UTC, spinel commented on internal/app/config/config.go
> +type Config struct {
добавил

2021-09-19 10:42 UTC, spinel commented on cmd/shortener/main.go
> +	memory, _ := s.GetData()
освободил main, сделал один сторож, где происходит вся логика с inmemory storage

2021-10-04 17:42 UTC, merged