Sprint3
spinel/go-musthave-shortener pull request #2
Opened 2021-09-29 12:07 UTC by spinel

переделано все полностью

2021-09-30 17:51 UTC, iTiky requested changes
Не проходят go vet тесты и почти все авто-тесты покраснели (что-то пошло не так глобально). Необходимы доработки.

2021-09-30 17:51 UTC, iTiky commented on internal/app/handler/middleware/cookie.go
> +	secretKey = "102703av0grv8n4l"
Секрет прям в коде, не очень хорошо )
Такое либо через ENV-ы, либо вот так: https://blog.alexellis.io/inject-build-time-vars-golang/
Второй вариант плох тем, что через дизассемблер легко можно отыскать секрет.

2021-09-30 17:51 UTC, iTiky commented on internal/app/handler/middleware/cookie.go
> +		userUUID := uuid.New().String()
Лучше `var userUUID uuid.UUID`, а затем установить её в if-e. При каждом запросе генерить UUID в холостую не очень хорошая идея, т.к. не быстрая операция.

2021-09-30 17:51 UTC, iTiky commented on internal/app/handler/handler.go
> +func NewCreateJSONURLHandler(cfg *config.Config, repo repository.URLStorer) http.HandlerFunc {
Эта функция очень схожа с `NewCreateURLHandler`, тут явно напрашивается некое переиспользование кода. Это не требуется для работы, но я бы всё же вынес логику приложения на уровень `service`, а этот уровень (`API`) просто подготавливает вход и вызывает методы сервиса. Сервис, в свою очередь, содержит `storage` слой как одну из своих зависимостей.

2021-09-30 17:51 UTC, iTiky commented on internal/app/handler/handler.go
> +		if err != nil {
Лучше сначала проверить ошибку, а уже затем корректность полученного объекта. By default предполагается, что если возникла ошибка, другие возвращаемые значения невалидны.

2021-09-30 17:51 UTC, iTiky commented on internal/app/repository/storage.go
> +func NewStorage(cfg *config.Config) (*Storage, error) {
Если ты принимаешь указатель, лучше проверить его на `nil` прежде чем использовать. А лучше, не применять указатели там, где можно этого избежать. В данном случае ведь никто "снаружи" не может (и не должен) изменить этот конфиг.

2021-09-30 17:51 UTC, iTiky commented on internal/app/repository/storage.go
> +	if pgDB != nil {
Не очень понятна логика. Если нет `pgDB` разве это не критическое состояние, т.е. нужно падать?

2021-09-30 17:51 UTC, iTiky commented on internal/app/repository/repository.go
> +	CreateURL(*model.Entity) (*model.Entity, error)
Часть методов интерфейса контекстно-зависимы, а другие нет. Лучше придерживаться одного стиля.

2021-09-30 17:51 UTC, iTiky commented on internal/app/repository/pg/pg.go
> +	pgOpts, err := pg.ParseURL(cfg.DatabaseDSN)
Если `cfg == nil`, будет паника. Опять же, лучше придерживаться immutable подхода везде, где это возможно.

2021-09-30 17:51 UTC, iTiky commented on internal/app/repository/pg/url.go
> +		if err.Error() == pg.ErrNoRows.Error() { //not found
Лучше избегать прямого сравнения ошибок и использовать `errors.Is(err, targetErr)`, т.к. такое сравнение не всегда работает (не для всех пакетов).

2021-09-30 17:51 UTC, iTiky commented on internal/app/repository/pg/url.go
> +	defer tx.Close()
Мне кажется, тут должен быть `tx.Rollback()`

2021-09-30 17:51 UTC, iTiky commented on internal/app/model/entity.go
>  type Entity struct {
Как я рассказывал на вебинаре, модели лучше разделять меж слоями. В данном случае слой базы данных очень сильно пролез в модель (добавились методы хуков специфичные для PG реализации). Желательно их разнести и добавить конверторы.

2021-10-02 17:37 UTC, spinel commented on internal/app/handler/middleware/cookie.go
> +	secretKey = "102703av0grv8n4l"
я просто не знал как лучше получить конфиг в middleware, пока просто передал параметром, это норм вариант?

func CookieHandle(cfg *config.Config, next http.Handler) http.Handler

пофиксил

2021-10-02 18:30 UTC, spinel commented on internal/app/handler/middleware/cookie.go
> +		userUUID := uuid.New().String()
fixed

2021-10-02 19:00 UTC, spinel commented on internal/app/handler/handler.go
> +		if err != nil {
поправил, кстати, нормально вообще таким образом ловить not found?

		if entity == nil {
			http.Error(w, "entity not found", http.StatusNotFound)
			return
		}

2021-10-02 19:04 UTC, spinel commented on internal/app/repository/pg/url.go
> +	defer tx.Close()
точно. поправил. спасибо

2021-10-03 15:08 UTC, spinel commented on internal/app/repository/pg/url.go
> +		if err.Error() == pg.ErrNoRows.Error() { //not found
errors.Is(err, pg.ErrNoRows)
упорно отдает false 

err.Error() == pg.ErrNoRows.Error() 
true

в мануалах go-pg тоже вижу ==

не пойму почему

2021-10-03 15:54 UTC, spinel commented on internal/app/model/entity.go
>  type Entity struct {
сделал. спасибо. это полезно оч)

2021-10-04 16:48 UTC, iTiky commented on internal/app/repository/pg/url.go
> +		if err.Error() == pg.ErrNoRows.Error() { //not found
Очень странное поведение, если честно. Если не работает `errors.Is`, ну что поделать )
`err.Error() == pg.ErrNoRows.Error()` тут прямое сравнение строк (просто к слову).

2021-10-04 16:49 UTC, iTiky commented on internal/app/handler/handler.go
> +		if err != nil {
Если после проверки ошибки, то конечно. Ну т.е. если `err == nil`, указатель на `entity` может быть `nil` если объект не найден. Это ожидаемое и корректное поведение.

2021-10-04 16:53 UTC, iTiky approved these changes
👍 всё учтено и главное, разделение моделей по слоям. Я ответил на комменты и посмотри, пожалуйста, на новые комменты (может быть полезно).
Большая часть тестов - красная (включая go vet), но пока пропустим эту проверку.

2021-10-04 16:53 UTC, iTiky commented on cmd/shortener/main.go
> +		Handler: middleware.CookieHandle(cfg,
Ты тут делаешь некую цепочку middleware-ов. Так лучше не делать. Представь что их будет много, эта часть кода будет нечитабельна от слова совсем. Посмотри на https://github.com/go-chi/chi и `r.Use()` часть. Chi сам строит такую цепочку.

2021-10-04 17:42 UTC, merged