Sprint4
spinel/go-musthave-shortener pull request #3
Opened 2021-10-14 22:23 UTC by spinel

Миша, привет. я только взялся последний инкремент сделать.

вопросы:
- воркер для хранения очереди на удаление инициализирую в main, мне каж некрасиво, но не знаю как сделать правильнее
- проверять на то овнер ли текущий юзер того, что хочет удалить надо перед тем как добавить в очередь, тогда теряется смысл хранить в батч. либо кидать в очередь все подряд, а принадлежит ли оно юзеру проверять по факту
- сам вокрет в pkg закинул, по ощущению наверное не место там

2021-10-16 14:25 UTC, iTiky requested changes
Нужны доработки. Обрати внимание на авто-тесты и go-vet тесты, большая их часть - красная.

2021-10-16 14:25 UTC, iTiky commented on cmd/shortener/main.go
> +	workerCh := make(chan *model.BatchUserCode)
Выше по коду. Лучше не использовать паники, где они нужны. В данном случае неверный конфиг это не паника. Лучше заменить на `log.Fatal` с читабельным сообщением.

2021-10-16 14:25 UTC, iTiky commented on internal/app/pkg/worker.go
> +func NewWorkerBatchDelete(ctx context.Context, cfg config.Config, repo repository.URLStorer, ch chan *model.BatchUserCode) {
Worker сильно связан с repo, т.е. это не часть `pkg` (обычно в `pkg` находится то, чем пользуются разные модули).
1. Ты передаешь сюда конфиг всего приложения, что чересчур, т.к. область ответственности крайне размыта.
2. Кажется, что воркер должен быть частью repo, т.к. выполняет его бизнес-логику.
3. Обычно канал создают в этой функции и возвращают его, т.е. не делаешь инициализацию, вызываешь `go` и через `return` возвращаешь канал (если он кому-то нужен).

2021-10-16 14:25 UTC, iTiky commented on internal/app/pkg/worker.go
> +		if batchItemsCounter >= batchQueueSize {
В этом месте `len(batchQueue) == 1` и проверка провалится, если `batchQueueSize == 1`.

2021-10-16 14:25 UTC, iTiky commented on internal/app/pkg/worker.go
> +		batchQueue = append(batchQueue, <-ch)
Честно говоря, первый раз вижу такую форму. Чаще всё же пишут так:
```go
for item := range <-ch {
    batchQueue = append(batchQueue, item)
}
```

2021-10-16 14:25 UTC, iTiky commented on internal/app/pkg/worker.go
> +		batchItemsCounter++
`batchItemsCounter` кажется лишней сущность, т.к. у тебя есть `len(batchQueue)`, который выполняет ту же роль.

2021-10-16 14:25 UTC, iTiky commented on internal/app/pkg/worker.go
> +		batchItemsCounter++
Более того, через `batchQueue[:0]` ты сбрасываешь `len` в 0, т.е. `len` может работать как счетчик.

2021-10-16 14:25 UTC, iTiky commented on internal/app/pkg/worker.go
> +	var batchQueue []*model.BatchUserCode
Я бы сделал так `batchQueue := make([]*model.BatchUserCode, 0, cfg.BatchQueueSize`. Таким образом `cap(batchQueue)` задан и можно проверять заполнена ли очередь через `len() == cap()`

2021-10-16 14:25 UTC, iTiky commented on internal/app/pkg/worker.go
> +func NewWorkerBatchDelete(ctx context.Context, cfg config.Config, repo repository.URLStorer, ch chan *model.BatchUserCode) {
4. Канал с указателями - это очень плохая идея. Кто-то "снаружи" может изменить данные в очереди.

2021-10-16 14:25 UTC, iTiky commented on internal/app/pkg/worker.go
> +		if batchItemsCounter >= batchQueueSize {
1. Если приложение будет закрыто, удаление не будет произведено. Необходим flush при graceful shutdown.
2. Если размер очереди 10 и пришёл лишь 1 запрос на удаление. Когда будет фактическое удаление? Я бы добавил периодический flush по времени.

2021-10-16 14:25 UTC, iTiky commented on internal/app/pkg/worker.go
> +					entities = append(entities, *entity)
Тут может быть паника, т.к. ты может попытаться разименовать `nil` объект. Выше есть проверка, да, но что если ровно между этими двумя строками придёт GC и почистит память? Immutable подход избавляет от этих проблем.

2021-10-16 14:25 UTC, iTiky commented on internal/app/pkg/worker.go
> +			err := repo.DeleteBatch(ctx, entities)
Лучше придерживаться Go-стиля:
```go
if err := repo.DeleteBatch(ctx, entities); err != nil {
}
```

2021-10-16 14:25 UTC, iTiky commented on internal/app/pkg/worker.go
> +			err := repo.DeleteBatch(ctx, entities)
Ты используешь тот же контекст, что был передан в воркер, т.е. фактически ограничения по времени выполнения этой операции быть не может. Этот воркер живет столько, сколько живет приложение, т.о. передавать ему контекст на вход - не лучшая идея. Я об этом рассказывал на 2-ом вебинаре.

2021-10-16 14:25 UTC, iTiky commented on internal/app/repository/pg/url.go
> +		return err
Я всегда советую добавлять контекст в ошибку. Когда ты будешь дебажить логи с прода, это может быть огромной проблемой, т.к. не ясно в какой части этой функции произошла ошибка. Когда кодовая база станет больше, держать в голове все возможные места возникновения ошибок невозможно, лучше себе помогать как можно раньше =)

2021-10-16 14:25 UTC, iTiky commented on internal/app/handler/handler.go
> +		err = json.Unmarshal(body, &codes)
```go
if err := json.Unmarshal(body, &codes); err != nil {
}
```
Это более читабельный и компактный вариант.

2021-10-16 14:25 UTC, iTiky commented on internal/app/handler/handler.go
> +func NewDeleteBatchHandler(cfg config.Config, repo repository.URLStorer, ch chan *model.BatchUserCode) http.HandlerFunc {
Лучше не передавать каналы между разными слоями приложения. Заместо этого можно добавить метод `func (repo URLStorer) EnqueueDelete(codes []string) error`, т.о. ты скроешь подкапотное пространство бизнес-логики от API-слоя.

2021-10-17 14:02 UTC, spinel commented on cmd/shortener/main.go
> +	workerCh := make(chan *model.BatchUserCode)
спасибо. поправил везде.

2021-10-17 14:48 UTC, spinel commented on internal/app/pkg/worker.go
> +		batchQueue = append(batchQueue, <-ch)
поправил.

2021-10-17 15:05 UTC, spinel commented on internal/app/handler/handler.go
> +		err = json.Unmarshal(body, &codes)
+

2021-10-17 18:14 UTC, spinel commented on internal/app/handler/handler.go
> +func NewDeleteBatchHandler(cfg config.Config, repo repository.URLStorer, ch chan *model.BatchUserCode) http.HandlerFunc {
да, я сначала не понял как это реализовать, сейчас сложилось вроде.

2021-10-17 18:24 UTC, spinel commented on internal/app/pkg/worker.go
> +			err := repo.DeleteBatch(ctx, entities)
ctx в крутящийся вечно воркер нельзя, но вызывать из него методы, требующие ctx надо, значит внутри него создать пустой контекст?
пока так сделал

2021-10-17 18:30 UTC, spinel commented on internal/app/pkg/worker.go
> +func NewWorkerBatchDelete(ctx context.Context, cfg config.Config, repo repository.URLStorer, ch chan *model.BatchUserCode) {
1. новый воркер на уровне репо принимает только размер очереди;
2. да, перенес, поначалу тупанул и не понял как
3. тут не понял, правильно ли я в итоге сделал в переделке...
4. переделал

2021-10-17 18:43 UTC, spinel commented on internal/app/pkg/worker.go
> +		batchItemsCounter++
да, что-то я упустил это. спасибо

2021-10-17 18:43 UTC, spinel commented on internal/app/pkg/worker.go
> +		if batchItemsCounter >= batchQueueSize {
ага. поставил проверку до.

2021-10-17 18:59 UTC, spinel commented on internal/app/pkg/worker.go
> +					entities = append(entities, *entity)
не знаю тогда как быть. если переделывать urlRepo.GetURL, там удобны проверки на nil вместо пустой структуры, либо тут делать мапу поинтеров, что тоже так себе...

2021-10-17 19:05 UTC, spinel commented on internal/app/repository/pg/url.go
> +		return err
вот так нормальный вариант? через точку: слой.метод wrap
return errors.Wrap(err, "repo.SaveBatch")

2021-10-19 19:18 UTC, iTiky approved these changes
Супер! Оставил комменты по косметике. Пожалуйста, поправь тесты, они всё краснее и краснее =)

2021-10-19 19:18 UTC, iTiky commented on internal/app/repository/pg/url.go
> +		return errors.Wrap(err, "repo.SaveBatch")
Я бы посоветовал так:
```go
return fmt.Errorf("repo.SaveBatch: %w", err)
```
Такая форма более читабельна, плюс схожа с `Printf`. `%w` как раз делает Wrap.

2021-10-19 19:18 UTC, iTiky commented on internal/app/repository/pg/url.go
> +			urlRepo.WorkerDeleteChan <- batchUserCode
Я бы добавил буфер к `urlRepo.WorkerDeleteChan`, т.к. тут будет постоянный лок на запись. Буфер ускорит этот процесс.

2021-10-19 19:18 UTC, iTiky commented on internal/app/repository/pg/url.go
> +	go func() {
Я бы убрал из функции `go func()`, т.к. из-за этого отступа очень трудно воспринимать код. Если функция названа `worker` ожидается что её нужно стартовать через `go`, т.е. `go repo.batchDeleteWorker` в момент создания репо.

2021-10-19 19:18 UTC, iTiky commented on internal/app/repository/pg/url.go
> +		var batchQueue []model.BatchUserCode
В этом месте ты знаешь размер слайда, лучше сделать преаллокацию тут же, т.е.:
```go
batchQueue := make([]model.BatchUserCode, 0, batchQueueSize)
```

2021-10-19 19:18 UTC, iTiky commented on internal/app/repository/pg/url.go
> +			if len(batchQueue) >= batchQueueSize {
```suggestion
			if len(batchQueue) == cap(batchQueue) {
```

2021-10-19 19:18 UTC, iTiky commented on internal/app/repository/pg/url.go
> +				now := time.Now()
```suggestion
				now := time.Now().UTC()
```

2021-10-19 19:18 UTC, iTiky commented on internal/app/repository/pg/url.go
> +				now := time.Now()
Я очень сильно советую прям приучиться добавлять UTC везде, где работаешь со временем. Это избавит от возможных проблем. Клиент прислал тебе время, ты его распарсил в `time.Time` и его же указал в каком-либо поле. А в другом месте ты используешь локальное время (`time.Now()`) и БАБАХ, у тебя перемешались таймзоны. Просто совет.

2021-10-19 19:18 UTC, iTiky commented on internal/app/repository/repository.go
> +	EnqueueDelete(codes []string, userUUID uuid.UUID) error
Отличный нейминг!

2022-03-11 11:55 UTC, merged